# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 17:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import tires.utils.functions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(1)])),
                ('width', models.PositiveSmallIntegerField(help_text='mm', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
                ('height', models.PositiveSmallIntegerField(help_text='mm', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)])),
                ('diameter', models.PositiveSmallIntegerField(help_text='mm', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1999)])),
                ('speed_index', models.CharField(max_length=5, validators=[django.core.validators.MinLengthValidator(1)])),
                ('picture', models.ImageField(upload_to=tires.utils.functions.get_file_path)),
            ],
        ),
    ]
