# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import tires.utils.functions


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='picture',
            field=models.ImageField(blank=True, upload_to=tires.utils.functions.get_file_path),
        ),
    ]
