# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import tires.utils.functions


class Migration(migrations.Migration):

    dependencies = [
        ('tires', '0003_auto_20170922_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=tires.utils.functions.get_file_path),
        ),
    ]
